### ISSUE TITLE
Problem with nessus6_scan_demo.py 

### ISSUE THREAD

**Issue by jgamblin** [averagesecurityguy/Nessus6#1]
After cloning your repo I get this error.   

Login
Traceback (most recent call last):
  File "nessus6_scan_demo.py", line 258, in <module>
    token = login(username, password)
  File "nessus6_scan_demo.py", line 65, in login
    return data['token']
TypeError: string indices must be integers, not str

**Comment by averagesecurityguy** [comment]
There may be an error on the login. Are you sure you have the correct url, username, and password?

**Comment by jgamblin** [comment]
I know username and password are right.  I am trying to login to Nessus Cloud at :
https://us-2a.svc.nessus.org/nessus6.html#/  

Do you know if it responds the same?

**Comment by averagesecurityguy** [comment]
It should. Make sure that you use the url https://us-2a.svc.nessus.org in the Python script.

**Comment by averagesecurityguy** [comment]
You don't need the :8834 on the URL for the cloud service.

**Comment by jgamblin** [comment]
Removing the :8834 and running pip install requests[security] fixed the errors! Thanks for the help! : )
