### ISSUE TITLE
Error about invalid Credentials 

### ISSUE THREAD

**Issue by 123rootwold** [averagesecurityguy/Nessus6#2]
I try to run autonessus script but after scan perform 40% to 45% i get error about invalid credentials . it is error 401 request. 
i try to trace back that time i got in get_scan_history function data['info'] get null value so it is show that error. so how i can solve that problem.  

`def get_scan_history(sid, hid):
    """
    Scan history details
    Get the details of a particular run of a scan.
    """
    params = {'history_id': hid}
    data = connect('GET', '/scans/{0}'.format(sid), params)
    return data['info']`

![2016-07-05 12_33_33-kali-linux-2 0 0-vm-amd64 - vmware workstation 12 player non-commercial use onl](https://cloud.githubusercontent.com/assets/20294936/16576530/6abb841e-42ad-11e6-9f3d-69605969c503.png)

**Comment by averagesecurityguy** [comment]
The AutoNessus tool is written by a different group, they used some of my code as the basis for their tool but I don't maintain any of their code base. I see that you have already opened an issue with them so I am closing this issue.

**Comment by 123pal** [comment]
Ok @averagesecurityguy . Thank you .

**Comment by parthaajayreddy** [comment]
@averagesecurityguy I am getting "unable to connect to remote server" when I execute the test function with my user id and password by hitting the localhost:8834. Am I missing to make any changes in your script before I run it on my system?

**Comment by averagesecurityguy** [comment]
@parthaajayreddy What version of Nessus are you using? Nessus 7 adds restrictions to the API, so I'm not sure these scripts will still work with Nessus 7.

In the future, please open up a new issue instead of adding a comment to a closed issue. It ensures your request is more easily seen.

**Comment by averagesecurityguy** [comment]
Tenable disabled API access in Nessus 7. There is nothing you can do.
